### ISSUE TITLE
Use preset=gui didn't get mesh 

### ISSUE THREAD

**Issue by mathmax12** [tum-vision/tandem#8]
Hi,
I can successfully generate the mesh obj on the Euroc dataset.
My problem is when I set preset=gui I can get some frames showing on a window but didn't see the mesh in the same window.
Could you let me know the culprit?
Thanks.
![image](https://user-images.githubusercontent.com/32367611/147694662-5ac1e3c0-8366-4b14-8ebe-4260384f0ef8.png)

**Comment by Ruinmou** [comment]
@mathmax12 Hello, do you know what is in camera.txtgroundtruth_tum_rgbd.txtposes_gt.txt? I have just touched this part, not very clear

**Comment by lkskstlr** [comment]
Hi @mathmax12,

I am not 100% sure what the issue is here or what you are seeing. The screenshot you posted looks like a debugging image from the original DSO code and not like the TANDEM output. This usually appears when pressing control buttons on the left side of the pangolin window. Normally the mesh should just show up in pangolin after some frames needed for initialisation.

On EuRoC are you also using `preset=gui`? Do you mean the `mesh.obj` generated in the results folder or a live mesh display?

If you could send me your full config, I can have look. I am still at my parent's place so I could do an in-depth check next week.

Best
Lukas

**Comment by mathmax12** [comment]
@hai8023 I am also new to this area. Sorry for that.

**Comment by mathmax12** [comment]
@lkskstlr 
Thank you for helping. No worries! 
_"On EuRoC are you also using preset=gui? Do you mean the mesh.obj generated in the results folder or a live mesh display?"_
The above window is gotten when I run Tandem on EuRoC and use preset=gui. I want to see the live mesh display.
Sorry for the confusion.
This is the script I used to get the above window. The only change I made is assign "gui" to preset.
![image](https://user-images.githubusercontent.com/32367611/147964694-605230c8-848e-4001-bd71-472a0f534976.png)

**Comment by lkskstlr** [comment]
Hi @mathmax12,

no worries. I am sorry of the code doesn't work for you as expected :)

I just tried the exact same change and was able to get the GUI with mesh (I had to use X11 forwarding because I am currently in home office, therefore it might look slightly different then the videos we show).

One thing I could imagine is that you accidentally pressed one of the buttons on the left, which will give you further debugging output similar to the image you showed. Maybe you can make sure that this isn't the case. You can also compare to the screenshot. If all this doesn't help you can send me an e-mail to `lukas.koestler` at `tum.de` and I can see if I can help you over zoom.

Best
Lukas

![Screenshot 2022-01-04 at 12 15 39](https://user-images.githubusercontent.com/14993470/148051878-1b3ec0d9-b36c-43e4-8dca-4fb526696a67.png)

**Comment by mathmax12** [comment]
@lkskstlr 
I found the forwarding x11 on my side doesn't work as expected.
It works well now when displaying the gui on the machine where the program run.
Thanks.
